language: node_js
node_js:
  - "10.15.0"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm test

after_success:
  - npm run coverage

notifications:
  webhooks: https://coverals.io/webhook
