FORMAT: 1A
HOST: https://solomon-sendit-api.herokuapp.com/

# SendIT API

SendIT is a courier service that helps users deliver parcels to different destinations. It provides courier quotes based on weight categories.

## Authentication [/auth]

### Signup a New User [POST /api/v1/auth/signup]

You may signup a new user using this action. It takes a JSON
object containing a user's credentials for the creation of a new account.

+ Request (application/json)

        {
            "firstName": "John",
            "lastName": "Doe",
            "phoneNumber": "07010000000",
            "email": "john.doe@email.com",
            "password": "john123",
            "category": "Regular"
        }

+ Response 201 (application/json)

        {
            "status": "success",
            "message": "Account created for John Doe",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImNhdGVnb3J5IjoiUmVndWxhciIsImlhdCI6MTU2NzAwODQwOSwiZXhwIjoxNTY3MjY3NjA5LCJpc3MiOiJTZW5kSVQifQ.IgtwNGJFYjJSE2ORHAY0xz8mstOzInZbJY-QXOzJlxI"
        }
        

### Login a User [POST /api/v1/auth/login]

You may login a user using this action. It takes a JSON
object containing a user's credentials.

+ Request (application/json)

        {
            "email": "john.doe@email.com",
            "password": "john123"
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "message": "John Doe is logged in",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImNhdGVnb3J5IjoiUmVndWxhciIsImlhdCI6MTU2NzAwODU1NywiZXhwIjoxNTY3MjY3NzU3LCJpc3MiOiJTZW5kSVQifQ.DQUZjnTv6ssYjQVeG3bvPTHQ5mWJlI_-SaEQY5xOPyg"
        }